name: Node.js CI/CD

on:
  push:
    branches: [ main, setup-workflow ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      
      - name: List repository contents
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Git status:"
          git status
          echo "Tracked files:"
          git ls-files
      
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install Dependencies
        run: |
          if [ -f "frontend/package.json" ]; then
            cd frontend
            npm ci
          else
            echo "Error: package.json not found in frontend directory"
            echo "Frontend directory contents:"
            ls -la frontend/
            exit 1
          fi
      
      - name: Build
        run: |
          if [ -d "frontend" ]; then
            cd frontend
            npm run build
          else
            echo "Frontend directory not found"
            exit 1
          fi
      
      - name: Deploy to Firebase
        if: success()
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROMPTDUMP }}'
          channelId: live
          projectId: promptdump