name: Node.js CI/CD

on:
  push:
    branches: [ main, setup-workflow ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Debug Directory
        working-directory: .
        run: |
          echo "Root directory contents:"
          ls -la
          echo "Frontend directory contents:"
          ls -la frontend
          
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROMPTDUMP }}'
          channelId: live
          projectId: promptdump
          entryPoint: frontend